name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Cho phép kích hoạt thủ công từ giao diện GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '9.3.1'

    - name: Decode Debug Keystore
      run: |
        echo "MIIKZgIBAzCCChAGCSqGSIb3DQEHAaCCCgEEggn9MIIJ+TCCBcAGCSqGSIb3DQEHAaCCBbEEggWtMIIFqTCCBaUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFAUJUTzSpGFI7ARlteBmBV9Nrc3qAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQZitnOokqUviXoSpwASQA/ASCBNAAZYmpG9s16uViX/3NwngealbFeJADVBSGmnGf722X2tYBcLM7yTqF40HoaxF5gRNzeDlkNlSbRwivo21edMt9s5z51jSJnuhCgDQa9m4/5p7NudBK7sZrcxG22SPfX5Cg2nGLisURPQMctUjjAol1bPvglIH1BZYXsRXS2ntzmZyC2DKk6eO4eRudptEwaNLrSwO2w/+xGZsDFMMi1kJYMy5fqwSAgaUdyWg4lBAJBs2WTq4rcza6kUoQGA2DUV4MLqqwZ0AEnCL6bqjvQBypr6DwDNeTEW/9OelCYdoQxmqgRMUCcwsLfEV1TAd9zaDq3lm9GnsGAdVnWhQZEIl/1b5qNeeWJ9od/gaWUY0DAZC7v+4vNvqvhYElZhJgInlPO8N7ZPhyWeLb7G0L0QZ9uUqMlzP7XVS+Bag7tsZL1v+tKIu+nb0IqMo5XUKr4rj8kvg9dT4LYFaBx4ONv4QaMBFAKQgWeBz5jEVbaG/kmp0BBB1l62eC0PiqAoawkmwPqK8lbDoXxRrss9AkeoyaI2sBs4/LK0urgg1iAdiCkSrECqYSKgjZcr0Jik7ezT5nSDkMoxIPB3UxOjv0hpPRXADbg98iouFfL5v9SUBA503JwXB8mDX0IzWKFvypYDuiqOW8TmEz2qS5UoAY3Grwf/N61HgB46S/t+yoHif36DvepTYzJBDkAIYxoqUviAjZLiXbmY9+lWx1z/r9d++HcEiIPcEWUgyxP3YkXqFAB1tjgc516GzXK8dnn7434FOmafNE0e7dYlEUmJx15MobXHQkJqiP1St3YyrQ9IQZYiNpYDKlkFGIHsnNY9bndY2PXlgquIZUdnOP2bGY+Bpy36ZpqcSEi937Jr9BnDqnidk9Xem2BaFwUXfuReKjecDjN9AxF8PcqUMOESqayvNpqqVhsFIBHTJR8/x+wtKSm7qghWvp2x3zoTwwkewWKArq1W6JJqxTbsBACd1Sx3N0cORnEQXpvIjbpYVrgWqx2AmprYqUB8Kaovv7LrhwuudssdS1jpKD/9l1y/kjRFSfnPJHJrp+AxCB0JyvwNcGN2V9UfFFrQZzSj7vBDf0Cuv7H+8g+jiS/5Bt08eKeFuY8aEKDa0kg030J4ku4bE1Exz+aLkqZLjVlt8AGqH9Rltmp2lpJdLz58/iI2QtvTA8YBkVgBaMJrvL7iAUKDtTOGPPy+Qp925AxL7SRfuTcutjoxCmhmPRNmry7xkxvVDOS7iX0nEvCaqhkgnih6YrfZxHsMsjrUSfhmmsArpZcMnxSZUrVPemssR2RaHblM86qPwRAutDEvOiboKU5qqITV8WsOSjnJw47St6Iz8grEUE8MOrGq7Jfqlkk7h7AhKP6ZF+2lXqvJCGBOBcMnYVmdWIdIhi6pi8z3W9b4Wsl3fg+RW+s6mm/+EdkeeD09YAzwoaIMPrdKJMgTlkdeIo0OEmn3hhzA8ekjyQyPsJg3uN2VULaknbu5QQprlnM08AWRePO4dFz7PFvZT3wO+ns8i7Cc/hyPT1nnrt5Zb2aU+wPd+0TTZDiLxr+yCJoYecgd+9yeiDo1P1xso26lWuHXiyUB4IrY+dfTmwfgRZkgCgTasDzaJNVOzNLX8cBzCe8jPCcl0piliLIXSjOaVdjDFSMC0GCSqGSIb3DQEJFDEgHh4AYQBuAGQAcgBvAGkAZABkAGUAYgB1AGcAawBlAHkwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTc4Mzk0NDA4MjM4OTCCBDEGCSqGSIb3DQEHBqCCBCIwggQeAgEAMIIEFwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBSxINDvAksUXrC6NcTCV43oi4Jn/wICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEM46PXt0ljOKfESjw3A8pxKAggOgfkyaDWzGrpIUguRuAi8Grsnmydyx4K2SwCaS4S1ryXc+HIVYUtkkJj5EKO7DzV7BUqwaf1lXMbLtdMaOabGEw6EULMAVAfu1xM4KpnRKTvUOTsem4ibDpZwmBzo5j4duec3/op8k5ubSR1tQyRvVwUP8o47Wt4GiHXVPErKlZCTFCKbGDo1qJBFd56FDxs7F5duA5AT7G5LUvHjkSlS5ayp7KPx3LfVy9SBkxW56b3hqls+PMsy+jcxLMUctUK9llARtqQJ/KxtE51i23ez89NKdUufMa9n5jjn63g7kX0PS7NmRLDQccWuTXY7XsnL40/5Ax4TooIbFB0HYPi84YI/Xop0RwJ6o/qk+hy6LDNRdHmQEcCplSkJ7yYkXo9p0dlXLmK+UhC146u1qauNJDEQLaaDP48nV1hrX6qQKOvb4tERDksoNaSYv1Izyr/Jf4urEi1idVrROuEupncKTcY0yGJFEtmkCR7Rz17bJ2JrZgGIgG0Wyq3C6z0lU+F9wowZ8XPzYGYDhb7QXM3dHM3q2z/gW7KkOg5tP4Il8R2B12ldF8KDtwGMmKvgbOZ7/ya/wj27NMsc48hgY/ZLVm7waQYrrbve+O/N/IO/Jdj9svqgyJM9GiteyF/aeAMysVrX3E7O2fDcJcl6RJGKnwccVfs+JuDeyQL61EAaAqWx9jXNS/fiTLITkKV7wTYWI0TjWZxCqAXhSVkFhfXJUVC0JT/DC0l5eh79I0AvFak1daqAzbsLEdoH5siTCOrNV1cbPdD1Y5S/DT+IN7BK3Vu63Rb2tkVDkXm13WLiXnOHtWjQEDPlRHAMArkEqaaWgGrdDf47Bmm2X2z+0Xue0JcRkDiBHAz8pJVgt0xEf4S6u0hepVhT6aNVUyOUvUKQRfKD7EWIVehDzl6Qs7RG8L3i6AP7+VM7NU4x+MfR25xSNpViF0ninszSd8aS9ul8yg7IDj9J84qXqsRF8Zh7ws+kWTCBR8j8yKzUPe+kPnOyVMImGpKQtSnxJbjXSPtRYghDzNv2hI2occkKnAfReS0yaYbXYSJpsvwh0UBpIbOS6n/47BnaoxiByu82iGGg8bYakMeTn4Vmkrl5CGrxbWsk+A02PagHSQ2uBZpUjcQwUuJ9MsI4oLPnHpJf78GpqE39FX172J682/8ZQtlX8n7uQakrP3N6afaBv4sZY+J9WmQiXVajAZpD9IAEpoqEw/MdM62b9EuPjO7kvdBZYqjBNMDEwDQYJYIZIAWUDBAIBBQAEIHrM1KYDGEhuIgWJAEq1oQAknvQb/2Ut6yc9J5n+yHXzBBTpet0pG0CULZTAkLTokahUvEJMcwICJxA=" | base64 -d > debug.keystore

    - name: Build Debug APK
      run: gradle assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ToolVip-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
